### PR TITLE
Attempting to prevent the RHCafe spam attack

### PR DESCRIPTION
**Pull request by theninja1000**
These changes i have made are to prevent the RHCafe spam attack with over 1000 sent PMs to Shibboleet iirc and about 250 user comments posted.

I taken the code directly from the blargboard repo, if you notice any issues please comment and I will adjust the code.

### CODE REVIEW

**Comment by StapleButter** [comment]
this code won't work

**Comment by Super-toad65** [comment]
Also you should make it execute only if the user has less than X posts so it doesn't get much annoying.

**Comment by theninja1000** [comment]
RE StapleButter:
I noticed, let's see what I can do.

RE ST65:
what

**Comment by Super-toad65** [comment]
@theninja1000 You took the user array wrong. It's `$loguser` instead of `$loguserid`

**Comment by theninja1000** [comment]
What else?

**Comment by StapleButter** [comment]
you kids are cute but you're still pretty far away from being coders

**Comment by theninja1000** [comment]
ok

**Pull request closed without merging**
